### ISSUE TITLE
[Suggestion] Include Pandora's Box on the list of Categories

### ISSUE THREAD

**Issue by ItoKyoshiro** [Attack8/VaultHuntersJEIIntegration#5]
Hey there!
Probably is just me, but I like to use the Pandora's Box a lot and would be really cool to have the option to include it :D
I know is deprecated on the modpack since streamers don't use them anymore (so maybe having it as a config option could work? :P)
Either way, the mod is really useful :)

**Comment by Attack8** [comment]
Sure! I’ll add it to my list for v0.5
